language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t buetze/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true buetze/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucker_name: "elasticbeanstalk-us-east-1-684344175438"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  sercret_access_key: "$AWS_SECRET_KEY"